#!/bin/sh

fatal()
{
    echo "Error: $*" >&2
    exit 1
}


register_cades(){
    W_SYSTEM32_DLLS_WIN="C:\\windows\\syswow64"    # path to access 32-bit dlls on win32/win64
    W_SYSTEM64_DLLS_WIN64="C:\\windows\\system32"  # path to access 64-bit dlls from 64-bit apps

    PREFIXARCH="$(grep '#arch' $WINEPREFIX/system.reg | cut -d "=" -f2)"

    echo "32-bit cades.dll has been registered"
    case $PREFIXARCH in
        win64)
            echo "Registering 64-bit cpcsp_proxy.dll ..."
            "$WINE" regsvr32 /s /n /i cpcsp_proxy.dll || fatal "64-bit cpcsp_proxy.dll has not been registered"
            echo "64-bit cpcsp_proxy.dll has been registered"

            echo "Registering 32-bit cpcsp_proxy.dll ..."
            "$WINE" "${W_SYSTEM32_DLLS_WIN}\\regsvr32.exe" /s /n /i cpcsp_proxy.dll || fatal "32-bit cpcsp_proxy.dll has not been registered"
            echo "32-bit cpcsp_proxy.dll has been registered"
            ;;
        *)
            echo "Registering 32-bit cpcsp_proxy.dll ..."
            "$WINE" regsvr32 /s /n /i cpcsp_proxy.dll || fatal "32-bit cpcsp_proxy.dll has not been registered"
            echo "32-bit cpcsp_proxy.dll has been registered"
            ;;
    esac
}

# Использование стандартного пути к wine, если он не был задан
[ -n "$WINE" ] || export WINE="/usr/bin/wine"

# Использование стандартного пути к префиксу wine, если он не был задан
[ -n "$WINEPREFIX" ] || export WINEPREFIX="$HOME/.wine"

# Если нет system.reg, завершить wineserver, чтобы не было проблем с определением архитектуры префикса
[ -e "$WINEPREFIX/system.reg" ] || wineserver -k

register_cades
