@ stdcall CPAcquireContext(ptr str long ptr)
@ stdcall CPCreateHash(long long ptr long ptr)
@ stdcall CPDecrypt(long long long long long ptr ptr)
@ stdcall CPDeriveKey(long long long long ptr)
@ stdcall CPDestroyHash(long long)
@ stdcall CPDestroyKey(long long)
@ stdcall CPDuplicateHash(long long ptr long ptr)
@ stdcall CPDuplicateKey(long long ptr long ptr)
@ stdcall CPEncrypt(long long long long long ptr ptr long)
@ stdcall CPExportKey(long long long long long ptr ptr)
@ stdcall CPGenKey(long long long ptr)
@ stdcall CPGenRandom(long long ptr)
@ stdcall CPGetHashParam(long long long ptr ptr long)
@ stdcall CPGetKeyParam(long long long ptr ptr long)
@ stdcall CPGetProvParam(long long ptr ptr long)
@ stdcall CPGetUserKey(long long ptr)
@ stdcall CPHashData(long long ptr long long)
@ stdcall CPHashSessionKey(long long long long)
@ stdcall CPImportKey(long ptr long long long ptr)
@ stdcall CPReleaseContext(long long)
@ stdcall CPSetHashParam(long long long ptr long)
@ stdcall CPSetKeyParam(long long long ptr long)
@ stdcall CPSetProvParam(long long ptr long)
@ stdcall CPSignHash(long long long wstr long ptr ptr)
@ stdcall CPVerifySignature(long long ptr long long wstr long)
@ stdcall CryptDllConvertPublicKeyInfo(long ptr long long ptr ptr)
@ stdcall CryptDllEncodePublicKeyAndParameters(long str ptr long long ptr ptr ptr ptr ptr)
